version: '3.0'
services:
  web:
    # TODO: build context, ports and redis dependency
    build:
      context: .
    volumes:
      - .:/code
    depends_on:
      - redis
    ports:
      - 5000:5000   
    environment:
      # Makes flask to reload code on change
      FLASK_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
     
  redis:
    image: redis:6.0-rc3
    volumes:
      - ./data:/data
    ports:
      - 6379:6379
